### ISSUE TITLE
Support for CS Fixer 2.16

### ISSUE THREAD

**Issue by rcerljenko** [mlocati/php-cs-fixer-configurator#11] opened 2019-11-04 06:26 UTC
PHP CS Fixer 2.16 was released yesterday with new features. Can you add support for them?  :)
https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases

**Comment by mlocati** [comment] 2019-11-04 08:02
Fixed by ae01e03ea13096194896a7cf26f31db3c4c7fce1

PS @rcerljenko don't worry about notifying me about new php-cs-fixer versions: I receive notifications whenever new versions are released, and I usually update php-cs-fixer-configurator as soon as possible (see the [commit history](https://github.com/mlocati/php-cs-fixer-configurator/commits/master):wink:)

**Closed by mlocati** 2019-11-04 08:02 UTC

**Comment by simivar** [comment] 2020-02-26 13:35
@mlocati what do you think about automating it with GitHub Actions or service like that?

**Comment by mlocati** [comment] 2020-02-26 14:53
Well, we'd need an hook configured in the [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) repository that invokes that GitHub action.
The problem is that I like to manually review the changes; furthermore PHP-CS-Fixer isn't updated so often...
